site_name: labtech
repo_url: https://github.com/ben-denham/labtech/
site_description: Documentation for labtech
nav:
  - README: 'README.md'
  - Tutorial: 'tutorial.md'
  - Cookbook: 'cookbook.md'
  - Labs and Tasks: 'core.md'
  - Diagramming: 'diagram.md'
  - Caches and Storage: 'caching.md'
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 2
            docstring_section_style: list
            members_order: source
            show_root_heading: true
            show_signature_annotations: true
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: material
  custom_dir: mkdocs_overrides
  features:
    - navigation.tracking
    - navigation.sections
  logo: images/icon.svg
  favicon: images/icon.png
extra_css:
    - stylesheets/extra.css
