name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        resolution: ["highest"]
        include:
          - python-version: "3.11"
            os: "ubuntu-latest"
            resolution: "lowest-direct"


    steps:
      - uses: actions/checkout@v3

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ">=0.5.28"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python --version
          uv sync --resolution ${{ matrix.resolution }}

      - name: Build
        run: |
          make build

      - name: Lint
        run: |
          uv run ruff --version
          make lint

      - name: Typecheck with mypy
        run: |
          uv run mypy --version
          make mypy

      - name: Test with pytest
        run: |
          uv run pytest --version
          make test
